import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { liquidSelectionRect } from "../components/LiquidSelection.tsx";

const host = { left: 20, top: 100, width: 280, height: 500 };
const target = { left: 24, top: 180, width: 272, height: 68 };
assert.deepEqual(liquidSelectionRect(host, target), { x: 4, y: 80, width: 272, height: 68 });
assert.deepEqual(liquidSelectionRect({ ...host, top: -300 }, { ...target, top: -220 }), liquidSelectionRect(host, target), "outer scroll cannot displace the highlight relative to the target");
assert.deepEqual(liquidSelectionRect(host, { ...target, width: 160, height: 40 }), { x: 4, y: 80, width: 160, height: 40 }, "resized or wrapped targets supply the real shape");
const css = readFileSync(new URL("../liquid-glass.css", import.meta.url), "utf8");
assert.match(css, /\.liquid-selection\s*\{[^}]*pointer-events:\s*none/);
assert.match(css, /transition:\s*transform 440ms/);
assert.match(css, /@keyframes liquid-flow-y/); assert.match(css, /@keyframes liquid-flow-x/);
assert.match(css, /\.liquid-selection-skin\s*\{[^}]*overflow:\s*hidden/, "moving glint cannot create a horizontal scrollbar");
const reduced = css.slice(css.indexOf("@media (prefers-reduced-motion: reduce)"), css.indexOf("@media (forced-colors: active)"));
assert.match(reduced, /\.liquid-selection\s*\{\s*transition:\s*none/);
assert.match(reduced, /\.liquid-selection-skin.*animation:\s*none/);
const memory = readFileSync(new URL("../components/MemoryDialog.tsx", import.meta.url), "utf8");
const image = readFileSync(new URL("../components/ImageView.tsx", import.meta.url), "utf8");
const sidebar = readFileSync(new URL("../components/ProjectSidebar.tsx", import.meta.url), "utf8");
assert(memory.includes("<LiquidSelection container={navigationRail}"));
assert(memory.includes("overflow-x-hidden overflow-y-auto"));
assert(image.includes('<LiquidSelection container={modeRail} activeKey={modeKey} axis="horizontal"'));
assert.match(sidebar, /key=\{scope\} ref=\{selectionRail\} className="conversation-selection-rail"/, "project/provider changes reset the decorative selection instead of flowing across scopes");
assert.match(sidebar, /activeKey=\{currentSessionId \? `\$\{currentProvider\}:\$\{currentSessionId\}` : null\}/, "new chat has no stale selected capsule");
assert.match(sidebar, /data-liquid-key=\{`\$\{s.provider\}:\$\{s.sessionId\}`\}/, "selection keys are provider-scoped, never list indexes");
assert.match(sidebar, /layoutKey=\{sessions.map/, "reordering/removal updates the selected position even at the same list length");
assert.match(css, /\.conversation-selection-rail:has\(> \.liquid-selection\) \.conversation-row\[aria-current="true"\]/);
assert.doesNotMatch(css, /\.conversation-selection-rail\s*\{[^}]*\b(?:filter|backdrop-filter|contain|transform)\s*:/, "sharing dialogs keep their viewport positioning");
assert(sidebar.includes("{ root: el.parentElement, threshold: 0.1 }"));
assert.match(sidebar, /<\/div>\s*\{\(sessions.length >= limit/, "pagination sentinel stays outside the non-scrolling animation rail");
console.log("Memory, image modes and conversation sidebar share an elastic selection without changing scrolling, scope or actions");
