import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { paneMotionVisibility, PANE_MOTION_MS } from "./usePaneMotion.ts";

assert.equal(PANE_MOTION_MS, 280);
assert.deepEqual(paneMotionVisibility(false, false, false), { present: false, expanded: false });
assert.deepEqual(paneMotionVisibility(true, false, false), { present: true, expanded: false }, "entry mounts the zero-width phase before expanding");
assert.deepEqual(paneMotionVisibility(true, true, true), { present: true, expanded: true });
assert.deepEqual(paneMotionVisibility(false, true, true), { present: true, expanded: false }, "logical close collapses immediately while retaining exit content");
assert.deepEqual(paneMotionVisibility(true, true, false), { present: true, expanded: false }, "rapid reopening reuses the mounted content before reversing");
assert.deepEqual(paneMotionVisibility(false, true, true, false), { present: false, expanded: false }, "fullscreen/maximized close bypasses disclosure animation");
const app = readFileSync(new URL("../App.tsx", import.meta.url), "utf8");
const dock = readFileSync(new URL("../components/RightDock.tsx", import.meta.url), "utf8");
const css = readFileSync(new URL("../liquid-glass.css", import.meta.url), "utf8");
const index = readFileSync(new URL("../index.css", import.meta.url), "utf8");
assert(app.includes('display: navMotion.present ? "flex" : "none"'));
assert(app.includes('pointerEvents: navOpen ? "auto" : "none"'));
assert(app.includes('narrow && !navOpen ? { inert: "" }'));
assert(app.includes('!narrow && !sidebarOpen ? { inert: "" }'));
assert(dock.includes('...(!open ? { inert: "" }'));
assert(dock.includes('pointerEvents: open ? "auto" : "none"'));
assert(dock.includes('width: !narrow && !maxed && !motion.expanded ? 0 : undefined'), "inline collapsed width wins over unlayered dock geometry");
assert(dock.includes('usePaneMotion(open, !maxed && !presenting)'));
assert(dock.includes('if (!motion.present && docs.length === 0) return null;'), "closed editors stay mounted, unlike empty content");
assert.match(css, /\.sidebar-disclosure\s*\{[^}]*transition:\s*width 280ms/);
assert.match(index, /body.resizing \.dockcol, body.resizing \.sidebar-disclosure\s*\{\s*transition:\s*none/);
assert.doesNotMatch(css, /\.(?:sidebar-disclosure|dock-overlay)\s*\{[^}]*\b(?:transform|backdrop-filter|filter|contain)\s*:/, "disclosures cannot anchor fixed child dialogs");
assert.match(css, /\.panel-toggle:active\s*\{[^}]*transform:\s*scale\(\.92\)/);
assert.match(css, /\.workbench-nav\[data-mobile-drawer="closed"\] \*\s*\{\s*pointer-events:\s*none !important/, "old WebViews cannot let a descendant override closed-pane hit protection");
assert.match(css, /prefers-reduced-motion: reduce[\s\S]*?\.sidebar-disclosure.*transition:\s*none/);
console.log("Both pane disclosures animate entry/exit without stale hitboxes, editor unmounts, delayed dragging or fullscreen traps");
