import assert from "node:assert/strict";
import { applySDKMessage, sessionMessagesToEvents } from "./processor.ts";
import { liveToolIds, showCodexActivity } from "./turn-activity.ts";
import type { ChatEvent } from "./types.ts";

let events: ChatEvent[] = [{ id: "u", type: "user", text: "列出记忆" }];
const emit = (phase: string, item: unknown) => { events = applySDKMessage(events, { type: phase, item }, () => {}); };
assert.equal(showCodexActivity(events, true), true, "quiet time before first output stays active");
emit("item.started", { id: "memory", type: "mcp_tool_call", server: "memory", tool: "list", arguments: {}, status: "in_progress" });
assert.equal(showCodexActivity(events, true), false, "tool spinner replaces thinking status");
assert.deepEqual([...liveToolIds(events, true)], ["s-codex-memory"]);
emit("item.completed", { id: "memory", type: "mcp_tool_call", server: "memory", tool: "list", arguments: {}, status: "completed", result: { content: [{ type: "text", text: '{"total":22}' }] } });
assert.equal(events.filter(e => e.type === "step").length, 1, "completion updates the same tool row");
assert.equal(showCodexActivity(events, true), true, "thinking resumes after the tool, even without more reasoning events");
assert.match((events[1] as Extract<ChatEvent,{type:"step"}>).output!, /22/);
assert.equal(showCodexActivity(events, false), false, "done/cancel/disconnect stops the spinner");
assert.deepEqual([...liveToolIds(events, false)], []);
emit("item.started", { id: "search", type: "web_search", query: "test" });
assert.equal((events[2] as Extract<ChatEvent,{type:"step"}>).status, "pending");
emit("item.completed", { id: "search", type: "web_search", query: "test" });
assert.equal((events[2] as Extract<ChatEvent,{type:"step"}>).status, "ok");
emit("item.completed", { id: "bad", type: "mcp_tool_call", server: "memory", tool: "save", status: "completed", result: { isError: true, content: [{ type: "text", text: "read_only" }] } });
assert.equal((events[3] as Extract<ChatEvent,{type:"step"}>).status, "error", "MCP business errors are not green successes");
emit("item.completed", { id: "reason", type: "reasoning", text: "A public reasoning summary" });
assert.equal((events[4] as Extract<ChatEvent,{type:"thinking"}>).status, "ok");
events.push({ id:"old",type:"step",tool:"CodexShell",status:"pending" }, { id:"new-u",type:"user",text:"another turn" });
assert.equal(showCodexActivity(events, true), true, "an unfinished historic tool cannot suppress the next turn");
assert.deepEqual([...liveToolIds(events, true)], []);
const history = sessionMessagesToEvents([{ provider:"codex",prompt:"test",startedAt:1,events:[{type:"item.completed",item:{id:"m",type:"mcp_tool_call",server:"memory",tool:"list",status:"completed",result:{content:[]}}}] }]);
assert.equal(showCodexActivity(history, false), false);
const waiting: ChatEvent[] = [{id:"s-call",type:"step",tool:"Bash",status:"pending"},{id:"p",type:"permission",permissionId:"p",tool:"Bash",input:{},toolUseId:"call"}];
assert.equal(showCodexActivity(waiting, true), false);
assert.deepEqual([...liveToolIds(waiting, true)], [], "approval wait is not tool execution");
