import assert from "node:assert/strict";
import type { Stats } from "node:fs";
import { SessionSummaryCache } from "./session-summary-cache.ts";
import type { SessionSummary } from "./session-store.ts";

const stat = (mtimeMs = 1, size = 1, ino = 1, ctimeMs = 1) => ({ mtimeMs, size, ino, ctimeMs }) as Stats;
let calls = 0;
const read = async (): Promise<SessionSummary> => ({ sessionId: String(++calls), provider: "claude", summary: "title", lastModified: 1 });
const cache = new SessionSummaryCache<SessionSummary>(2, 1024);
await cache.get("a", stat(), read);
await cache.get("a", stat(), read);
assert.equal(calls, 1);
await cache.get("a", stat(2), read);
await cache.get("a", stat(2, 2), read);
await cache.get("a", stat(2, 2, 2), read);
await cache.get("a", stat(2, 2, 2, 2), read);
assert.equal(calls, 5, "mtime, size, inode and ctime changes all invalidate metadata");
await cache.get("b", stat(), read);
await cache.get("c", stat(), read);
await cache.get("a", stat(2, 2, 2, 2), read);
assert.equal(calls, 8, "bounded LRU evicts oldest metadata");
cache.prune(new Set(["b"]));
await cache.get("c", stat(), read);
assert.equal(calls, 9, "removed native files cannot retain cached entries");
let resolve!: (value: SessionSummary) => void;
let concurrentReads = 0;
const pending = new SessionSummaryCache<SessionSummary>();
const delayed = () => { concurrentReads++; return new Promise<SessionSummary>((r) => { resolve = r; }); };
const a = pending.get("a", stat(), delayed), b = pending.get("a", stat(), delayed);
await Promise.resolve();
assert.equal(concurrentReads, 1);
resolve(await read());
assert.deepEqual(await a, await b);
let failures = 0;
await assert.rejects(pending.get("bad", stat(), async () => { failures++; throw new Error("fail"); }));
await pending.get("bad", stat(), read);
assert.equal(failures, 1, "failed reads do not poison cache");
let nullReads = 0;
const nullable = async () => ++nullReads === 1 ? null : read();
await pending.get("transient", stat(), nullable);
assert(await pending.get("transient", stat(), nullable));
assert.equal(nullReads, 2, "transient null results must be retried even without a file timestamp change");
let largeReads = 0;
const large = async () => ({ ...(await read()), firstPrompt: "x".repeat(4096), summary: String(++largeReads) });
await cache.get("large", stat(), large);
await cache.get("large", stat(), large);
assert.equal(largeReads, 2, "oversized prompts bypass admission rather than exceed the byte budget");
console.log("session-summary-cache.test.ts ✓");
